services:
  mmb-api:
    container_name: mmb-api
    restart: always
    image: ${REGISTRY}/mmb-aspnet:latest
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - /home/khai-npm/cs.env
    ports:
      - 8080:8080
    profiles:
      - prod
    networks:
      mmb-networks:
        
  mmb-api-build:
    image: ${REGISTRY}/mmb-aspnet:latest
    build:
      context: ../
      dockerfile: Dockerfile
    profiles:
      - build
networks:
  mmb-networks:
    name: mmb-networks
    external: true