name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build Docker Images
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase repository name
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REGISTRY=ghcr.io/$REPO_LOWER" >> $GITHUB_ENV
      - name: Build Docker Images
        run: |
          docker compose -f .docker/compose.yaml --profile build build --parallel
          docker compose -f .docker/compose.yaml --profile build push

  deploy:
    name: Deploy API
    needs: build-image
    runs-on: [self-hosted]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository name
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REGISTRY=ghcr.io/$REPO_LOWER" >> $GITHUB_ENV
          
      - name: Deploy API
        run: docker compose -f .docker/compose.yaml --profile prod pull

      - name: Deploy API
        run: docker compose -f .docker/compose.yaml --profile prod -p mmb-application up -d
      
      - name: Prune Docker Images
        run: docker image prune -a -f

      - name: Notify Deployment Success
        run: echo "Deployment completed successfully!"